/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rdict.h"

#include "client_impl.h"



void rdictprog_1(char *host) {
  CLIENT *clnt;


#ifndef DEBUG
  clnt = clnt_create(host, RDICTPROG, RDICTVERS, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  handle_initw(clnt);
  handle_insertw(clnt);
  handle_array_example(clnt);
  handle_matrix_example(clnt);

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
  char *host;

  if (argc < 2) {
    printf("usage: %s server_host\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  rdictprog_1(host);
  exit(0);
}
