/**
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 *
 * I modified this file to simplify all the stuff that the
 * original author did so that you can see how simple things
 * can be.
 *
 * Here we just launch the main and then call the 4 handlers
 *   handle_initw(clnt);
 *   handle_insertw(clnt);
 *   handle_array_example(clnt);
 *   handle_matrix_example(clnt);
 *
 * I prefer it this way because if you are generating frequently
 * as you build your project, you will need to be copying and pasting
 * into this file frequently (I'm sure there is a better way to handle
 * this, perhaps don't compile with -a).
 *
 * Anyway, keeping this file small, and extracting the functionality
 * out to the client_impl.h file made it easier to copy and paste
 * without having to grab a huge amount of code every time.
 */

#include "rdict.h"

#include "client_impl.h"

void rdictprog_1(char *host) {
  CLIENT *clnt;

#ifndef DEBUG
  clnt = clnt_create(host, RDICTPROG, RDICTVERS, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  handle_initw(clnt);
  handle_insertw(clnt);
  handle_array_example(clnt);
  handle_matrix_example(clnt);

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
  char *host;

  if (argc < 2) {
    printf("usage: %s server_host\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  rdictprog_1(host);
  exit(0);
}
