/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include "rdict.h"

#include <rpc/rpc.h>
#include <string.h>

char dict[DICTSIZ][MAXWORD + 1];
static char snd[50];
static int lns;
int nwords = 0;

// prototypes 
int deletew(char *), lookupw(char *);

// implement rpc calls
bool_t initw_1_svc(void *w, int *ptr_retcode, struct svc_req *rqstp) {
  nwords = 0;
  *ptr_retcode = 1;
  return (TRUE);
}

bool_t insertw_1_svc(char **w, int *ptr_retcode, struct svc_req *rqstp) {
  strcpy(dict[nwords], *w);
  nwords++;
  *ptr_retcode = nwords;
  return (TRUE);
}

bool_t deletew_1_svc(char **w, int *ptr_retcode, struct svc_req *rqstp) {
  *ptr_retcode = deletew(*(char **)w);
  return (TRUE);
}

bool_t lookupw_1_svc(char **w, int *ptr_retcode, struct svc_req *rqstp) {
  *ptr_retcode = lookupw(*(char **)w);
  return (TRUE);
}

int rdictprog_1_freeresult(SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result) {
  xdr_free(xdr_result, result);
  return (1);
}


int deletew(char *word) {
  int i;
  for (i = 0; i < nwords; i++)
    if (strcmp(word, dict[i]) == 0) {
      nwords--;
      strcpy(dict[i], dict[nwords]);
      return 1;
    }
  return 0;
}

int lookupw(char *word) {
  int i;
  for (i = 0; i < nwords; i++)
    if (strcmp(word, dict[i]) == 0)
      return 1;
  return 0;
}

